name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: engineerd/configurator@v0.0.5
      with:
        name: docfx.exe
        pathInArchive: docfx.exe
        url: https://github.com/dotnet/docfx/releases/download/v2.56.6/docfx.zip
    - name: List stuff
      run: dir .
    - name: Testing
      run: docfx -h 
