name: Archive & upload template without demo

on:
  release:
    types:
      - created

jobs:
  build:
    name: Archive & upload template without demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Put tag in environment variable
        run: |
          echo "HEAD_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
      - name: Archive template and license
        run: |
          zip -r discordfx-${{ env.HEAD_TAG }}.zip README.md LICENSE discordfx
      - name: Upload archive
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./discordfx-${{ env.HEAD_TAG }}.zip
          asset_name: discordfx-${{ env.HEAD_TAG }}.zip
          asset_content_type: application/zip
